# Generated by Django 6.0.7 on 2026-07-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=10, unique=True)),
                ('callsign', models.CharField(blank=True, max_length=10, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_following', models.BooleanField(default=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('followed_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='radar.followedaircraft')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
